### ISSUE TITLE
A BF/FP converter

### ISSUE THREAD

**Issue by JaredMFProgramming** [juju2143/flufflepuff#3]
Hello there! :smiley: I wrote a program that converts BF to FP, and FP to BF.  I call it "Project Chrysalis", and it is a bit buggy, so beware if you try to use it.

Anyways, you can find it [here.](https://gist.github.com/JaredMFProgramming/a914a5a22cb893c913ec7c0a84d602d2)

**Comment by juju2143** [comment]
Well, that's a simple thing to do. FP to BF, kinda harder, though. Thanks, I'll add it to the list.
